### ISSUE TITLE
Quotations not consistent.

### ISSUE THREAD

**Issue by Kaholaz** [Sanseer/Robatim#1]
Inconsistent use of single and double quotes. Here is an example from main.py:
```python
parser.add_argument('-t', "--tonic")
parser.add_argument('-m', "--mode")
parser.add_argument("-s", "--style", default="Mm")
```
Consider fixing this and setting a guideline to make the code easier to read and to collaborate on.

**Comment by Sanseer** [comment]
Thanks for the feedback. Those are typos. I'm planning on rebuilding the code from scratch, so I'll address this and other mistakes.

**Comment by Sanseer** [comment]
fixed in latest [commit](https://github.com/Sanseer/Robatim/commit/f8f7b2ce8785c0523729b98c2fba6840b10f6439).
